version: 0.2
phases:
   install:
      runtime-versions:
         java: openjdk11
      commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install -y maven
      finally:
      - echo This always runs even if the update or install command fails         
   pre_build:
      commands:
      - echo Nothing to do in the pre_build phase...
   build:
      commands:
      - echo Build started on `date`
      - cd MyFirstAWS
      - mvn install
   post_build:
      commands:
      - echo Build completed on `date`
      - ls -ltr
artifacts:
   files:
   - target/samples-1.0.0.jar